// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/helloworld.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_d7a4c88bf3e73d14, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_d7a4c88bf3e73d14, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "proto.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/proto.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/helloworld.proto",
}

func init() {
	proto.RegisterFile("grpc/proto/helloworld.proto", fileDescriptor_helloworld_d7a4c88bf3e73d14)
}

var fileDescriptor_helloworld_d7a4c88bf3e73d14 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xb1, 0x4b, 0xc5, 0x30,
	0x10, 0xc6, 0xa9, 0xa8, 0xb5, 0xa7, 0x8b, 0x71, 0x29, 0x75, 0xb0, 0x74, 0x90, 0x4e, 0x29, 0xd4,
	0xc9, 0xc1, 0xc1, 0x49, 0xe7, 0xea, 0x2a, 0x92, 0xb6, 0x67, 0x14, 0x12, 0x13, 0x93, 0x2b, 0xd2,
	0xff, 0xfe, 0xf1, 0x92, 0x06, 0xde, 0x9b, 0xee, 0xee, 0xe3, 0xf7, 0xfd, 0x38, 0xb8, 0x95, 0xce,
	0x4e, 0x9d, 0x75, 0x86, 0x4c, 0xf7, 0x8d, 0x4a, 0x99, 0x7f, 0xe3, 0xd4, 0xcc, 0x43, 0xc0, 0xce,
	0xc2, 0xa8, 0xee, 0xa4, 0x31, 0x52, 0x61, 0xa4, 0xc6, 0xe5, 0xab, 0xa3, 0x1f, 0x8d, 0x9e, 0x84,
	0xb6, 0x91, 0x6b, 0x3e, 0xe0, 0xea, 0x75, 0xdf, 0x1d, 0xf0, 0x6f, 0x41, 0x4f, 0x8c, 0xc1, 0xe9,
	0xaf, 0xd0, 0x58, 0x66, 0x75, 0xd6, 0x16, 0x43, 0xd8, 0xd9, 0x23, 0xc0, 0xe4, 0x50, 0x10, 0xce,
	0x9f, 0x82, 0xca, 0x93, 0x3a, 0x6b, 0x2f, 0xfb, 0x8a, 0x47, 0x33, 0x4f, 0x66, 0xfe, 0x9e, 0xcc,
	0x43, 0xb1, 0xd1, 0xcf, 0xd4, 0xdc, 0x03, 0x6c, 0x7a, 0xab, 0x56, 0x56, 0x42, 0xae, 0xd1, 0x7b,
	0x21, 0x93, 0x3f, 0x9d, 0xfd, 0x13, 0xe4, 0x2f, 0x0e, 0x91, 0xd0, 0xb1, 0x1e, 0x2e, 0xde, 0xc4,
	0x1a, 0x5a, 0xec, 0x26, 0xea, 0xf9, 0xe1, 0x8b, 0xd5, 0xf5, 0x71, 0x68, 0xd5, 0x3a, 0x9e, 0x87,
	0xe4, 0x61, 0x17, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x95, 0x92, 0xfd, 0x13, 0x01, 0x00, 0x00,
}
